version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yehia
      POSTGRES_DB: circleConnect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Community Service
  community-service:
    build: ./CircleConnect-Community
    ports:
      - "3000:3000"  # Host:Container port
    env_file:
      - ./CircleConnect-Community/.env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: